routes/web.php
<?php

use App\Jobs\SendSms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\EventProgramController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CustomerReviewController;
use App\Http\Controllers\ResolutionCenterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/login', [HomeController::class, 'index']);
Route::post('/login', [LoginController::class, 'sendLoginResponse'])->name('login');
Route::post('/register', [RegisterController::class, 'register'])->name('register');
Route::get('/register', [HomeController::class, 'index'])->name('register');
Route::get('/home', [HomeController::class, 'index'])->middleware(['auth', 'auth.session']);
Route::post('/search', [HomeController::class, 'searchServices'])->name('home.search');
Route::post('/search-event', [HomeController::class, 'searchEvents'])->name('home.event.search');
Route::get('/search-results/all', [HomeController::class, 'showSearchResults'])->name('search.show');
Route::post('/search-results', [HomeController::class, 'search'])->name('global.search');
Route::get('/auth/facebook', [SocialController::class, 'facebookRedirect'])->name('facebook.login');
Route::get('/auth/facebook/callback', [SocialController::class, 'facebookLogin']);
Route::get('/auth/google', [SocialController::class, 'redirectToGoogle'])->name('google.login');
Route::get('/auth/google/callback', [SocialController::class, 'handleGoogleCallback']);
Route::get('/forgot-password', [ResetPasswordController::class, 'enterEmail'])->name('password.request')->middleware('guest');
// Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email');
Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email.confirm');
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [ResetPasswordController::class, 'passwordUpdate'])->middleware('guest')->name('password.update');
Route::post('/dispute', [HomeController::class, 'fileDispute'])->name('dispute');
Route::resource('/resolution-center', ResolutionCenterController::class);
Route::post('/resolution-center/response', [ResolutionCenterController::class, 'issueResponse'])->middleware(['auth'])->name('resolution-center.response');

Route::get('/set-credentials', [UserController::class, 'setCredentials'])->name('set-credentials')->middleware('auth');
Route::post('/submit-credentials', [UserController::class, 'submitCredentials'])->name('submit-credentials')->middleware('auth');

Route::get('/set/phonenumber', [UserController::class, 'setPhoneNumber'])->name('set.phone');
Route::post('/submit/phonenumber', [UserController::class, 'submitPhoneNumber'])->name('submit.phone')->middleware('auth');
Route::get('/verify/phonenumber', [UserController::class, 'verifyPhoneForm'])->name('verify.phone');
Route::post('/phone/verify', [UserController::class, 'verifyPhoneNumber'])->name('submit.verify.phone')->middleware('auth');

// Route::get('/event/user/{email}/{eventId}/{role}/register', [HomeController::class, 'eventUserRegister'])->name('register.event.user');
Route::get('/event/{eventId}/user/{email}', [HomeController::class, 'eventUserRegister'])->name('register.event.user');

Route::get('/event/ticket/{guest}', [HomeController::class, 'ticket'])->name('event.ticket.show');
Route::post('/ticket/{ticket}/attended/guests', [EventController::class, 'eventTicketUpdateGuestsAttended'])->middleware(['auth', 'auth.session'])->name('event.guests.attended');
Route::post('/ticket/{ticket}/payment', [EventController::class, 'ticketPayment'])->name('ticket.payment');
Route::get('/event/guest/invite/{guest}', [HomeController::class, 'guestTicket']);

Auth::routes(['verify' => true, 'login' => false, 'register' => false]);

Route::view('/email/verify', 'verify')->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
   $request->fulfill();
   return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/resend/code', function() {
   SendSms::dispatch(Auth::user()->phone_number, 'Your verification code is '.Auth::user()->phone_verification_code);
   return redirect()->back()->with('success', 'Verification code sent');
});

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/faq', [SupportController::class, 'index'])->name('faq');
Route::get('vendor/view/{id}', [HomeController::class, 'viewVendor'])->name('vendor.view');
Route::get('user/profile/edit', [UserController::class, 'editProfile'])->name('user.profile.edit');
Route::post('user/profile/update', [UserController::class, 'updateProfile'])->name('user.profile.update');

Route::post('/customer-review', [CustomerReviewController::class, 'review'])->name('customer-review');

Route::group(['prefix' => 'events', 'as' => 'events.'], function () {
   Route::get('/', [EventController::class, 'index'])->name('index')->middleware(['auth', 'auth.session']);
   Route::get('/create', [EventController::class, 'create'])->name('create');
   Route::post('/store', [EventController::class, 'store'])->name('store');
   Route::post('/{id}/update', [EventController::class, 'update'])->name('update');
   Route::get('/{id}/show', [EventController::class, 'show'])->name('show')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/edit', [EventController::class, 'edit'])->name('edit')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/delete', [EventController::class, 'destroy'])->name('destroy')->middleware(['auth', 'auth.session']);
});

Route::get('/pricing/{id}', [CartController::class, 'getPricingPrice']);

Route::get('/messages', [MessagesController::class, 'index'])->name('messages');
Route::get('/messages/{orderID}', [MessagesController::class, 'chats'])->name('message.chat');
Route::post('/message/send', [MessagesController::class, 'store'])->name('message.send');
Route::post('/messages/name', [MessagesController::class, 'getUserName'])->name('message.user.name');

Route::group([
    'prefix' => 'client/',
    'as' => 'client.'
],function () {
   Route::get('/favorites', [HomeController::class, 'favorites'])->name('favorites');
    Route::post('create/event', [EventController::class, 'createEvent'])->name('create.event');
    Route::get('create/program', [HomeController::class, 'createProgram'])->name('create.program');
    Route::post('submit/program',  [HomeController::class, 'submitProgram'])->name('submit.program');
    Route::get('services/{category?}', [ServiceController::class, 'clientServices'])->name('services.all');
    Route::post('services', [ServiceController::class, 'clientServicesFiltered'])->name('services.filtered');
    Route::get('service/{service}', [ServiceController::class, 'clientService'])->name('service.one');
    Route::get('add-to-cart/{service}/{pricing?}', [ServiceController::class, 'addToCart'])->name('add-to-cart');
    Route::delete('remove-from-cart', [ServiceController::class, 'removeFromCart'])->name('remove-from-cart');
    Route::get('user/cart', [ServiceController::class, 'viewCart'])->name('user.cart');
    Route::get('event/{event}/tasks', [EventController::class, 'eventTasks'])->name('event.tasks')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/orders', [EventController::class, 'eventOrders'])->name('event.orders')->middleware(['auth', 'auth.session']);
    Route::get('/order/{order}', [OrderController::class, 'order'])->name('orders.order')->middleware(['auth', 'auth.session']);
    Route::post('event/order/delete', [EventController::class, 'deleteEventOrder'])->name('event.order.delete')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/add', [EventController::class, 'addEventTask'])->name('event.tasks.add')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/edit', [EventController::class, 'editEventTask'])->name('event.tasks.edit')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/gifts', [EventController::class, 'eventGifts'])->name('event.gifts');
    Route::post('event/{event}/gifts/gift/add', [EventController::class, 'addEventGift'])->name('event.gift.add')->middleware(['auth', 'auth.session']);
    Route::post('event/{gift}/gifts/gift/update', [EventController::class, 'updateEventGift'])->name('event.gift.update')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/guest/list', [EventController::class, 'eventGuestList'])->name('event.guests')->middleware(['auth', 'auth.session']);

resources/views/add-phone-number.blade.php
@extends('layouts.master')
@section('title', 'Set Password')
@section('content')
<div class="container">
   <br>
   <div class="row">
   <div class="col-lg-2"></div>
   <div class="col-lg-8">
      <div class="billing-form">
         <h2>Phone Number</h2>
         <form class="form" action="{{ route('submit.phone') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="field-group">
               <div class="row">
                  <div class="col-md-12">
                        <div class="field-input">
                           <label for="name">Enter Your Phone Number<span class="required">*</span></label>
                           <input type="number" placeholder="Enter phone number" name="phone_number" required>
                           <x-input-error for="phone_number"></x-input-error>
                        </div>
                  </div>
               </div>
            </div>
            <div class="field-submit">
               <input type="submit" value="Submit" id="add-event" class="btn">
            </div>
         </form><!-- .billingForm -->
      </div><!-- .checkout-form -->
   </div>
   <div class="col-lg-2"></div>
</div>
</div>
<br>

@endsection

resources/views/cart.blade.php
@extends('layouts.master')
@section('title', 'Cart')
@section('css')
<style>
   .member-place-list.owner-booking td:nth-child(2) {
      width: 100%;
   }
   .cart-service-description {
      width: 75%;
   }
   @media only screen and (max-width: 998px) {
      .cart-service-description {
         width: 100%;
      }
   }
</style>
@endsection
@section('content')
<main id="main" class="site-main">
   <div class="site-content owner-content">
       <div class="container">
           <div class="member-place-wrap">
               <div class="member-wrap-top">
                   <h2>My Cart</h2>
               </div><!-- .member-wrap-top -->
               <div>
                  @if (session('cart'))
                  <p class="error">* Please note you will need to login before creating the order(s)</p>
                     <table class="member-place-list owner-booking table-responsive">
                        <thead>
                           <tr>
                             {{-- <th>#</th> --}}
                              <th class="cart-service-description">Service</th>
                              <th>Added To Cart</th>
                              <th>Select Quote</th>
                              {{-- <td class="table-width-250">Custom Message</td> --}}
                              <th>Actions</th>
                           </tr>
                        </thead>
                        <form action="{{ route('client.checkout') }}" method="post">
                           @csrf
                           <tbody>
                                 @foreach ($services as $service)
                                    <tr>
                                       <input hidden type="checkbox" name="service[{{ $service->id }}]" id="{{ $service->id }}" value="{{ $service->id }}" checked>
                                       <td hidden>
                                         {{-- <input type="checkbox" name="service[{{ $service->id }}]" id="{{ $service->id }}" value="{{ $service->id }}"> --}}
                                       </td>
                                       <td data-title="Service" class="cart-service-description">
                                             <a href="{{ route('client.service.one', $service) }}">
                                                <b>{{ $service->service_title }}</b>
                                             </a>
                                             <p class="cart-service-description">{{ $service->service_description }}</p>
                                       </td>
                                       <td data-title="Date added">
                                          {{ session('cart')[$service->id]['added_on']->diffForHumans() }}
                                       </td>
                                       <td data-title="Pricing">
                                          <select name="service_pricing[{{ $service->id }}]" id="" class="form-control">
                                             <option value="">Get Quote</option>
                                             @if ($service->service_pricing->count())
                                                @foreach ($service->service_pricing as $pricing)
                                                   <option value="{{ $pricing->id }}" @if (session('cart')[$service->id]['pricing'] == $pricing->id) selected @endif>{{ $pricing->service_pricing_title }} (Ksh.{{ $pricing->service_pricing_price }})</option>
                                                @endforeach
                                             @endif
                                          </select>
                                       </td>
                                       <td class="table-width-250 d-none" data-title="Message">
                                          <textarea name="order_message[{{ $service->id }}]" class="form-control" hidden></textarea>
                                       </td>
                                       <td>
                                          {{-- <span class="delete remove-from-cart" data-id="{{ $service->id }}" title="Delete"><i class="la la-trash-alt"></i></span> --}}
                                          <button class="btn delete remove-from-cart" data-id="{{ $service->id }}" title="Delete">Remove</button>
                                       </td>
                                    </tr>
                                 @endforeach
                           </tbody>
                        </table>
                        <input type="submit" value="Send" class="btn" style="float: right">
                     </form>
                  @else
                     <p>No Services found in cart.</p>
                  @endif
               </div>
           </div>
       </div>
   </div>
</main>
@push('scripts')
   <script>
      $(".remove-from-cart").click(function (e) {
            e.preventDefault();

            var ele = $(this);

            if(confirm("Are you sure")) {
                $.ajax({
                    url: '{{ route('client.remove-from-cart') }}',
                    method: "DELETE",
                    data: {_token: '{{ csrf_token() }}', id: ele.attr("data-id")},
                    success: function (response) {
                        window.location.reload();
                    }
                });
            }
        });
   </script>
@endpush
@endsection

resources/views/php.blade.php
<?php
echo phpinfo()
?>

resources/views/resolution-center.blade.php
@extends('layouts.master')
@section('title', 'Resolution Center')
@section('css')
   <style>
      .raised-issue {
         display: flex;
         justify-content: space-between
      }
      .raised-issue-details {
         display: flex;
      }
      .raised-issue img {
         width: 60px;
         height: 60px;
         margin-right: 10px;
         border-radius: 50%;
         object-fit: cover;
      }
      .raised-issue-actions {
         top: 0;
         right: 0;
      }
      .raised-issue-actions i, .raised-issue-actions p {
         background: #8FCA27;
         color: #fff;
         padding: 5px;
         border-radius: 3px;
      }
      .responses {
         background: rgb(233, 233, 233);
         padding: 15px;
         border-radius: 5px;
      }

      .response {
         display: flex;
         background: rgb(199, 199, 199);
         padding: 15px;
         border-radius: 5px;
         margin-bottom: 1px;
      }
      .responses > .admin-response {
         border: 3px solid rgb(84, 84, 84);
      }
      .responses > .admin-response img {
         border: 3px solid rgb(84, 84, 84);
      }
      .response-user-image {
         width: 60px;
         height: 60px;
         margin-right: 10px;
         border-radius: 50%;
         object-fit: cover;
      }
      .open-login, .open-signup {
         color: #23D3D3;
         cursor: pointer;
      }
      @media only screen and (min-width: 768px) {
         .mobile-heading {
            display: none;
         }
      }
      @media only screen and (max-width: 768px) {
         .response-user-image, .raised-issue img {
            display: none;
         }
         .mobile-heading {
            display: block;
            margin-top: 70px;
            text-align: center;
         }
         .desktop-heading {
            display: none;
         }
      }
   </style>
@endsection
@section('content')
<main id="main" class="site-main service-details">
   <div class="owner-page-wrap">
      <h1 class="mobile-heading">Resolution Center</h1>
      <div class="container">
         <div class="row">
            <div class="col-lg-4 col-md-5 col-sm-12">
               <div class="sidebar sidebar--shop sidebar--border">
                  <aside class="widget widget-shadow widget-reservation">
                     @auth
                        <form action="{{ route('resolution-center.store') }}" method="post" class="add-issue-form" id="add-issue-form">
                           @csrf
                           <div class="field-group field-input">
                              <label>Enter the description of your issue here</label>
                              <textarea name="issue" id="issue" class="form-control" rows="10"></textarea>
                           </div>
                           <br>
                           <input type="Submit" class="btn submit-issue" value="Submit">
                        </form>
                     @else
                        <div class="add-issue-form">
                           Please <span class="open-login" href="{{ route('login') }}">Login</span> or <span title="Sign Up" class="open-signup" href="{{ route('register') }}">Sign Up</span> to contribute
                        </div>
                     @endauth
                  </aside><!-- .widget-reservation -->
               </div><!-- .sidebar -->
            </div>
            <div class="col-lg-8 col-md-7 col-sm-12">
               <div class="place__left">
                  <div class="place__box place__box--npd">
                     <h1 class="desktop-heading">Resolution Center</h1>
                     @foreach ($issues as $issue)
                        @include('partials.resolution-center-response')
                        @include('partials.resolution-center-edit')
                        <div class="place-item layout-02 place-hover">
                           <div class="place-inner">
                              <div class="entry-detail">
                                 <div class="raised-issue">
                                    <div class="raised-issue-details">
                                       <img src="{{ $issue->user->getAvatar($issue->user->avatar) }}" alt="{{ $issue->user->f_name }}" class="avatar">
                                       <div class="package-description">
                                          <h5>{{ $issue->user->f_name }} {{ $issue->user->l_name }}</h5>
                                          <p>{{ $issue->issue }}</p>
                                          <p><strong>{{ $issue->created_at->diffForHumans() }}</strong></p>
                                       </div>
                                    </div>
                                    <div class="raised-issue-actions">
                                       @auth
                                          @if (auth()->user()->id === $issue->user_id)
                                             <i class="fas fa-pencil" id="edit-package" data-bs-toggle="modal" data-bs-target="#update-{{ $issue->id }}" style="cursor: pointer"></i>
                                          @else
                                             <p data-bs-toggle="modal" data-bs-target="#response-{{ $issue->id }}" style="cursor: pointer">Reply</p>
                                          @endif
                                       @endauth
                                    </div>
                                 </div>
                                 <hr>
                                 <div class="responses">
                                    <h3>Replies</h3>
                                    @forelse ($issue->raisedIssueResponses as $response)
                                       <div class="response @if($response->isAdminResponse) admin-response @endif">
                                          @if ($response->isAdminResponse)
                                             <img class="response-user-image" src="{{ config('services.app_url.admin_url').'/assets/images/user.png' }}" alt="">
                                          @else
                                             <img class="response-user-image" src="{{ $response->user->getAvatar($response->user->avatar) }}" alt="{{ $response->user->f_name }}" class="avatar">
                                          @endif
                                          <span class="response-text">
                                             @if (!$response->isAdminResponse)
                                                <h5>{{ $response->user->f_name }} {{ $response->user->l_name }}</h5>
                                             @endif
                                             <p>{{ $response->response }}</p>
                                             <p><strong>{{ $response->created_at->diffForHumans() }}</strong></p>
                                          </span>
                                       </div>
                                    @empty
                                       <span>No responses provided yet</span>
                                    @endforelse
                                 </div>
                              </div>
                           </div>
                        </div>
                        <br>
                     @endforeach
                  </div>
               </div><!-- .place__left -->
            </div>
         </div>
      </div>
   </div>
</main><!-- .site-main -->
@push('scripts')
   <script>
      function checkIfEmailInString(text) {
         var re = /(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/;
         return re.test(text.replace(/ /g,''));
      }

      function checkIfPhoneNumberInString(text) {
         var phoneExp = /(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?/img;
         return phoneExp.test(text.replace(/ /g,''))
      }

      $('.submit-issue').on('click', function (e) {
         e.preventDefault();
         let message = $('#issue').val()
         if (checkIfEmailInString(message)) {
            toastr.options =
               {
                  "closeButton" : true,
                  "progressBar" : true,
                  "positionClass" : "toast-bottom-right"
               }
            toastr.error("You cannot share contact information!!");

            return
         }
         if (checkIfPhoneNumberInString(message)) {
            toastr.options =
               {
                  "closeButton" : true,
                  "progressBar" : true,
                  "positionClass" : "toast-bottom-right"
               }
            toastr.error("You cannot share contact information!!");

            return
         }

         $('#add-issue-form').submit()
      })

      // $('#update-issue-submit-btn').on('click', function (e) {
      //    e.preventDefault();
      //    let message = $('.updated-issue').val()
      //    if (checkIfEmailInString(message)) {
      //       toastr.options =
      //          {
      //             "closeButton" : true,
      //             "progressBar" : true,
      //             "positionClass" : "toast-bottom-right"
      //          }
      //       toastr.error("You cannot share contact information!!");

      //       return
      //    }
      //    if (checkIfPhoneNumberInString(message)) {
      //       toastr.options =
      //          {
      //             "closeButton" : true,
      //             "progressBar" : true,
      //             "positionClass" : "toast-bottom-right"
      //          }
      //       toastr.error("You cannot share contact information!!");

      //       return
      //    }

      //    $('#update-issue-form').submit()
      // })

      // $('#issue-response-submit-btn').on('click', function (e) {
      //    e.preventDefault();
      //    let message = $('.issue-response').val()
      //    if (checkIfEmailInString(message)) {
      //       toastr.options =
      //          {
      //             "closeButton" : true,
      //             "progressBar" : true,
      //             "positionClass" : "toast-bottom-right"
      //          }
      //       toastr.error("You cannot share contact information!!");

      //       return
      //    }
      //    if (checkIfPhoneNumberInString(message)) {
      //       toastr.options =
      //          {
      //             "closeButton" : true,
      //             "progressBar" : true,
      //             "positionClass" : "toast-bottom-right"
      //          }
      //       toastr.error("You cannot share contact information!!");

      //       return
      //    }

      //    $('#issue-response-form').submit()
      // })
   </script>
@endpush
@endsection

resources/views/set-password.blade.php
@extends('layouts.master')
@section('title', 'Set Password')
@section('content')
<div class="container">
   <br>
   <div class="row">
   <div class="col-lg-2"></div>
   <div class="col-lg-8">
      <div class="billing-form">
         <h2>Set Password and Phone Number</h2>
         <p style="color: red">Please set a new password and enter your phone number. Your email is the current set password.</p>
         <form class="form" action="{{ route('submit-credentials') }}" method="POST" id="event_add" enctype="multipart/form-data">
            @csrf
            <div class="field-group">
               <div class="row">
                  <div class="col-md-6">
                        <div class="field-input">
                           <label for="name">Password<span class="required">*</span></label>
                           <input type="password" placeholder="Enter password" name="password" id="password" required>
                           <x-input-error for="password"></x-input-error>
                        </div>
                  </div>
                  <div class="col-md-6">
                     <div class="field-input">
                        <label for="name">Confirm Password<span class="required">*</span></label>
                        <input type="password" placeholder="Re-enter password" name="password_confirmation" id="password_confirm" required>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-md-12">
                        <div class="field-input">
                           <label for="name">Enter Your Phone Number<span class="required">*</span></label>
                           <input type="number" placeholder="Enter phone number" name="phone_number" required>
                           <x-input-error for="phone_number"></x-input-error>
                        </div>
                  </div>
               </div>
            </div>
            <div class="field-submit">
               <input type="submit" value="Submit" id="add-event" class="btn">
            </div>
         </form><!-- .billingForm -->
      </div><!-- .checkout-form -->
   </div>
   <div class="col-lg-2"></div>
</div>
</div>
<br>

@endsection

resources/views/test-image.blade.php
@extends('layouts.master')
@section('title', 'Upload Image')
@section('content')
<div class="container">
   <div class="site-main" id="main">
      <form action="{{ route('upload-image') }}" method="POST" enctype="multipart/form-data" >
         @csrf
         <div class="row">
             <div class="col-lg-4">
                 <div class="field-group field-file">
                     <label>Service Image</label>
                     <label class="preview">
                         <input type="file" name="image" accept=".jpg,.png,.jpeg" class="upload-file" data-max-size="50000">
                         <img class="img_preview" src="{{ asset('assets/images/no-image.png') }}" alt="" />
                         <i class="la la-cloud-upload-alt"></i>
                     </label>
                     <div class="field-note">Maximum file size: 5 MB.</div>
                     <x-input-error for="service_image"></x-input-error>
                 </div>
             </div>
         </div>
         <br>
         <input type="submit" value="Submit" class="btn">
      </form>
   </div>
</div>
@endsection