routes/web.php
<?php

use App\Jobs\SendSms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\EventProgramController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CustomerReviewController;
use App\Http\Controllers\ResolutionCenterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/login', [HomeController::class, 'index']);
Route::post('/login', [LoginController::class, 'sendLoginResponse'])->name('login');
Route::post('/register', [RegisterController::class, 'register'])->name('register');
Route::get('/register', [HomeController::class, 'index'])->name('register');
Route::get('/home', [HomeController::class, 'index'])->middleware(['auth', 'auth.session']);
Route::post('/search', [HomeController::class, 'searchServices'])->name('home.search');
Route::post('/search-event', [HomeController::class, 'searchEvents'])->name('home.event.search');
Route::get('/search-results/all', [HomeController::class, 'showSearchResults'])->name('search.show');
Route::post('/search-results', [HomeController::class, 'search'])->name('global.search');
Route::get('/auth/facebook', [SocialController::class, 'facebookRedirect'])->name('facebook.login');
Route::get('/auth/facebook/callback', [SocialController::class, 'facebookLogin']);
Route::get('/auth/google', [SocialController::class, 'redirectToGoogle'])->name('google.login');
Route::get('/auth/google/callback', [SocialController::class, 'handleGoogleCallback']);
Route::get('/forgot-password', [ResetPasswordController::class, 'enterEmail'])->name('password.request')->middleware('guest');
// Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email');
Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email.confirm');
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [ResetPasswordController::class, 'passwordUpdate'])->middleware('guest')->name('password.update');
Route::post('/dispute', [HomeController::class, 'fileDispute'])->name('dispute');
Route::resource('/resolution-center', ResolutionCenterController::class);
Route::post('/resolution-center/response', [ResolutionCenterController::class, 'issueResponse'])->middleware(['auth'])->name('resolution-center.response');

Route::get('/set-credentials', [UserController::class, 'setCredentials'])->name('set-credentials')->middleware('auth');
Route::post('/submit-credentials', [UserController::class, 'submitCredentials'])->name('submit-credentials')->middleware('auth');

Route::get('/set/phonenumber', [UserController::class, 'setPhoneNumber'])->name('set.phone');
Route::post('/submit/phonenumber', [UserController::class, 'submitPhoneNumber'])->name('submit.phone')->middleware('auth');
Route::get('/verify/phonenumber', [UserController::class, 'verifyPhoneForm'])->name('verify.phone');
Route::post('/phone/verify', [UserController::class, 'verifyPhoneNumber'])->name('submit.verify.phone')->middleware('auth');

// Route::get('/event/user/{email}/{eventId}/{role}/register', [HomeController::class, 'eventUserRegister'])->name('register.event.user');
Route::get('/event/{eventId}/user/{email}', [HomeController::class, 'eventUserRegister'])->name('register.event.user');

Route::get('/event/ticket/{guest}', [HomeController::class, 'ticket'])->name('event.ticket.show');
Route::post('/ticket/{ticket}/attended/guests', [EventController::class, 'eventTicketUpdateGuestsAttended'])->middleware(['auth', 'auth.session'])->name('event.guests.attended');
Route::post('/ticket/{ticket}/payment', [EventController::class, 'ticketPayment'])->name('ticket.payment');
Route::get('/event/guest/invite/{guest}', [HomeController::class, 'guestTicket']);

Auth::routes(['verify' => true, 'login' => false, 'register' => false]);

Route::view('/email/verify', 'verify')->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
   $request->fulfill();
   return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/resend/code', function() {
   SendSms::dispatch(Auth::user()->phone_number, 'Your verification code is '.Auth::user()->phone_verification_code);
   return redirect()->back()->with('success', 'Verification code sent');
});

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/faq', [SupportController::class, 'index'])->name('faq');
Route::get('vendor/view/{id}', [HomeController::class, 'viewVendor'])->name('vendor.view');
Route::get('user/profile/edit', [UserController::class, 'editProfile'])->name('user.profile.edit');
Route::post('user/profile/update', [UserController::class, 'updateProfile'])->name('user.profile.update');

Route::post('/customer-review', [CustomerReviewController::class, 'review'])->name('customer-review');

Route::group(['prefix' => 'events', 'as' => 'events.'], function () {
   Route::get('/', [EventController::class, 'index'])->name('index')->middleware(['auth', 'auth.session']);
   Route::get('/create', [EventController::class, 'create'])->name('create');
   Route::post('/store', [EventController::class, 'store'])->name('store');
   Route::post('/{id}/update', [EventController::class, 'update'])->name('update');
   Route::get('/{id}/show', [EventController::class, 'show'])->name('show')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/edit', [EventController::class, 'edit'])->name('edit')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/delete', [EventController::class, 'destroy'])->name('destroy')->middleware(['auth', 'auth.session']);
});

Route::get('/pricing/{id}', [CartController::class, 'getPricingPrice']);

Route::get('/messages', [MessagesController::class, 'index'])->name('messages');
Route::get('/messages/{orderID}', [MessagesController::class, 'chats'])->name('message.chat');
Route::post('/message/send', [MessagesController::class, 'store'])->name('message.send');
Route::post('/messages/name', [MessagesController::class, 'getUserName'])->name('message.user.name');

Route::group([
    'prefix' => 'client/',
    'as' => 'client.'
],function () {
   Route::get('/favorites', [HomeController::class, 'favorites'])->name('favorites');
    Route::post('create/event', [EventController::class, 'createEvent'])->name('create.event');
    Route::get('create/program', [HomeController::class, 'createProgram'])->name('create.program');
    Route::post('submit/program',  [HomeController::class, 'submitProgram'])->name('submit.program');
    Route::get('services/{category?}', [ServiceController::class, 'clientServices'])->name('services.all');
    Route::post('services', [ServiceController::class, 'clientServicesFiltered'])->name('services.filtered');
    Route::get('service/{service}', [ServiceController::class, 'clientService'])->name('service.one');
    Route::get('add-to-cart/{service}/{pricing?}', [ServiceController::class, 'addToCart'])->name('add-to-cart');
    Route::delete('remove-from-cart', [ServiceController::class, 'removeFromCart'])->name('remove-from-cart');
    Route::get('user/cart', [ServiceController::class, 'viewCart'])->name('user.cart');
    Route::get('event/{event}/tasks', [EventController::class, 'eventTasks'])->name('event.tasks')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/orders', [EventController::class, 'eventOrders'])->name('event.orders')->middleware(['auth', 'auth.session']);
    Route::get('/order/{order}', [OrderController::class, 'order'])->name('orders.order')->middleware(['auth', 'auth.session']);
    Route::post('event/order/delete', [EventController::class, 'deleteEventOrder'])->name('event.order.delete')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/add', [EventController::class, 'addEventTask'])->name('event.tasks.add')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/edit', [EventController::class, 'editEventTask'])->name('event.tasks.edit')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/gifts', [EventController::class, 'eventGifts'])->name('event.gifts');
    Route::post('event/{event}/gifts/gift/add', [EventController::class, 'addEventGift'])->name('event.gift.add')->middleware(['auth', 'auth.session']);
    Route::post('event/{gift}/gifts/gift/update', [EventController::class, 'updateEventGift'])->name('event.gift.update')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/guest/list', [EventController::class, 'eventGuestList'])->name('event.guests')->middleware(['auth', 'auth.session']);

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Event extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $attributes = [
        'status' => 'Active'
    ];

    protected $casts = [
        'event_start_date' => 'datetime',
        'event_end_date' => 'datetime',
        'isCorporate' => 'bool'
    ];

    public function getEventCoverImage(string $image)
    {
        return Storage::disk('event')->url('poster/'.$image);
    }

    /**
     * Get the user that owns the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get all of the event_tasks for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function event_tasks()
    {
        return $this->hasMany(EventTask::class);
    }

    /**
     * Get all of the gifts for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function gifts()
    {
        return $this->hasMany(Gift::class);
    }

    /**
     * Get all of the event_guests for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function event_guests()
    {
        return $this->hasMany(EventGuestDetail::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    /**
     * Get all of the budget for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function budget()
    {
        return $this->hasMany(Budget::class);
    }

    /**
     * Get all of the register for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function registers()
    {
      return $this->hasMany(Register::class);
    }

    /**
     * Get all of the event_users for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function event_users()
    {
        return $this->hasMany(EventUser::class);
    }

    /**
     * Get all of the user_roles for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function user_roles()
    {
        return $this->hasMany(UserRole::class);
    }

    /**
     * Get the program associated with the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function program()
    {
        return $this->hasOne(EventProgram::class);
    }

    /**
     * Get all of the registrationTickets for the Event
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function registrationTickets()
    {
        return $this->hasMany(RegisterTicket::class);
    }

    public function getGeneralAdmissionGuestCount()
    {
      return $this->event_guests->where('ticket_title', 'General Admission')->count();
    }

    public function setEventStatus()
    {
        if ($this->event_start_date > now()) {
            $this->status = "Active";
        } elseif ($this->event_start_date <= now() && $this->event_end_date >= now()) {
            $this->status = "Live";
        } elseif ($this->event_end_date < now()) {
            $this->status = "Past";
        }

        $this->save();
    }

    public function getEventStatus()
    {
        $this->setEventStatus();
        return $this->status;
    }

    public function getCoverImage(string $image)
    {
        return Storage::disk('service')->url('cover_image/'.$image);
    }
}

app/Models/EventTypes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EventTypes extends Model
{
    use HasFactory;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];
}

resources/views/events/budget-transactions.blade.php
@extends('layouts.master')
@section('title', 'Transactions')
@section('css')
<style>
   @media only screen and (max-width: 768px) {
      .member-statistical {
         margin-top: 50px;
      }
   }
</style>
@endsection
@section('content')
   <livewire:budget-transactions :event="$event" :budget="$budget" />
@endsection

resources/views/events/budget.blade.php
@extends('layouts.master')
@section('title', 'Event Budget')
@section('css')
<style>
   @media only screen and (max-width: 768px) {
      #budgets-container {
         margin-top: 20px;
         transition: .2s ease;
      }
      .budgets {
         transition: .2s ease;
      }
      .add-budget {
         margin-top: -15px !important;
      }
      .budget-to-dashboard {
         margin-top: -10px;
         margin-bottom: 15px;
      }
   }
   @media only screen and (max-width: 575px) {
      .budget-to-dashboard {
         margin-top: -10px;
         margin-bottom: 15px;
      }
   }
</style>
@endsection
@section('content')
<div>
   <main id="main" class="site-main">
      <div class="site-content owner-content">
         <div class="container">
            <div class="member-place-wrap">
               <div class="member-wrap-top mt-2">
                  <h2>{{ $event->event_name }}'s Budget and Expenses</h2>
                  <div>
                     <a class="btn budget-to-dashboard" href="{{ route('events.show', $event) }}">Back to My Event</a>
                     @if ($budgets->count() || $initial_budget->count())
                        <button class="btn m-2 add-budget" data-bs-toggle="modal" data-bs-target="#add-budget-{{ $event->id }}" style="background-color: #F58C1C">Add Budget</button>
                     @endif
                     @include('partials.add-budget')
                  </div>
               </div><!-- .member-place-wrap -->
               @if ( ! $budgets->count() && ! $initial_budget->count())
                  <div>
                     <i class="fas fa-money-check-alt" style="font-size: 50px"></i>
                     <p>Create a budget, top up and manage your event transactions</p>
                  </div>
                  <br>
                  <div class="row">
                     <div class="col-md-6">
                        <h3 class="modal-header-title">Add Initial Budget</h3>
                        <div class="login-form">
                           <div class="submit-section">
                              <div class="row">
                                    <div class="form-group col-md-12">
                                       <form action="{{ route('client.event.budget.initial.add') }}" method="POST" enctype="multipart/form-data" >
                                          @csrf
                                          <input type="hidden" name="event_id" value="{{ $event->id }}" id="">
                                          <div class="field-group field-input">
                                                <label for="company_logo">Title</label>
                                                <input type="text" name="title" class="form-control" value="Initial Budget" readonly required>
                                                <x-input-error for="title"></x-input-error>
                                          </div>
                                          <div class="field-group field-input">
                                             <label class="label">Amount *</label>
                                             <input type="number" min="1" name="amount" class="form-control" required>
                                             <x-input-error for="amount"></x-input-error>
                                          </div>
                                          <div class="field-group field-input">
                                                <h4 class="label">Description</h4>
                                                <textarea name="description" class="form-control" ></textarea>
                                                <x-input-error for="description"></x-input-error>
                                             </div>
                                          <br>
                                          <input type="submit" value="Submit" class="btn">
                                       </form>
                                    </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               @else
               <div class="member-statistical">
                  <div class="row">
                     <div class="col-lg-4 col-md-6 col-sm-12" id="pie-chart-container">
                        <div id="pie-chart"></div>
                     </div>
                     <div class="col-lg-8 col-md-6 col-sm-12" id="budgets-container">
                        <div class="row">
                           <div class="col-lg-3 col-md-6 col-sm-12">
                              <div class="item green">
                                 <a href="{{ route('client.event.budget.transactions', ['event' => $event, 'budget' => $initial_budget->budget_id]) }}">
                                    <h3>{{ $initial->title }}</h3>
                                    <h2>Balance: Ksh.<b>{{ number_format($initial_budget->amount) }}</b></h2>
                                    <span>{{ $initial_budget->created_at->diffForHumans() }}</span>
                                    <span class="line"></span>
                                 </a>
                                 {{-- <i class="las la-edit" data-bs-toggle="modal" data-bs-target="#edit-budget-{{ $initial_budget->id }}" style="cursor: pointer; font-size: 20px"></i> --}}
                                 {{-- <i class="la la-trash" data-bs-toggle="modal" data-bs-target="#delete-budget-{{ $budget->id }}" style="cursor: pointer; font-size: 20px"></i> --}}
                              </div>
                           </div>
                           @foreach ($budgets as $budget)
                              @include('partials.edit-budget')
                              @include('partials.delete-budget')
                              <div class="col-lg-3 col-6 budgets">
                                 <div class="item green">
                                    <a href="{{ route('client.event.budget.transactions', ['event' => $event, 'budget' => $budget]) }}">
                                       <h3>{{ $budget->title }}</h3>
                                       <h2>Balance: Ksh.<b>{{ number_format($budget->balance) }}</b></h2>
                                       <span>{{ $budget->created_at->diffForHumans() }}</span>
                                       <span class="line"></span>
                                    </a>
                                    <i class="las la-edit" data-bs-toggle="modal" data-bs-target="#edit-budget-{{ $budget->id }}" style="cursor: pointer; font-size: 20px"></i>
                                    <i class="la la-trash" data-bs-toggle="modal" data-bs-target="#delete-budget-{{ $budget->id }}" style="cursor: pointer; font-size: 20px"></i>
                                 </div>
                              </div>
                           @endforeach
                        </div>
                     </div>
                  </div>
               </div>
               @endif
            </div><!-- .member-wrap-top -->
         </div>
      </div><!-- .site-content -->
   </main><!-- .site-main -->
</div>
   @push('scripts')
   <script>
      let event_number = $('[id=event_number_view]')
      event_number.each((ind, obj) => {
         var num = obj.innerHTML.replace(/,/gi, "");
         var num2 = num.split(/(?=(?:\d{3})+$)/).join(",")
         obj.innerHTML = num2
      });
   </script>
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
         var data = google.visualization.arrayToDataTable([
            ['Category Name', 'Amount'],

               @php
                  foreach($chartData as $data) {
                        echo "['".$data['name']."', ".$data['amount']."],";
                  }
               @endphp
         ]);

         var options = {
            title: 'Expenditure Per Category',
            is3D: true,
            legend: 'bottom',
            width: 400,
            height: 300
         };

         var chart = new google.visualization.PieChart(document.getElementById('pie-chart'));

         chart.draw(data, options);
      }

      let chartData = {!! json_encode($chartData) !!}
      if (chartData.length == 0) {
         document.getElementById('pie-chart-container').setAttribute('hidden', 'hidden')
         document.getElementById('budgets-container').classList.remove('col-lg-8')
         document.getElementById('budgets-container').classList.remove('col-md-6')
         document.getElementById('budgets-container').classList.add('col-lg-12')
         document.getElementById('budgets-container').classList.remove('col-md-3')
      }
   </script>
   @endpush
@endsection

resources/views/events/event_orders.blade.php
@extends('layouts.master')
@section('title', 'Event Orders')
@section('css')
<style>
   @media only screen and (max-width: 768px) {
      .member-wrap-top .btn:nth-child(1) {
         margin-top: -180px !important;
      }
      .member-wrap-top .btn:nth-child(2) {
         margin-top: -180px !important;
      }
   }
   @media only screen and (max-width: 575px) {
      .member-wrap-top .btn:nth-child(1) {
         margin-top: -180px !important;
      }
      .member-wrap-top .btn:nth-child(2) {
         margin-top: -90px !important;
      }
   }
</style>
@endsection
@section('content')
    <livewire:event-orders-index :event="$event" />
@endsection

resources/views/events/events-roles.blade.php
@extends('layouts.master')
@section('title', 'Events')
@section('content')
   <div class="container">
      <div class="member-place-wrap">
         <div class="member-wrap-top">
            <h2>Events with Roles</h2>
         </div>
         <div>
            <table class="member-place-list owner-booking table-responsive">
               <thead>
               <tr>
                  <th class="table-width-200">Event Name</th>
                  <th>Event Type</th>
                  <th>Role</th>
                  <th>Status</th>
                  <th>Action</th>
               </tr>
               </thead>
               <tbody>
                  @foreach($roles as $role)
                     @include('partials.delete-event-role')
                     <tr>
                        <td data-title="Title" class="table-width-200">
                           <a href="{{ route('events.show', $role->event->id) }}" style="cursor: pointer">
                              {{ $role->event->event_name }}
                           </a>
                        </td>
                        <td data-title="Type">{{ $role->event->event_type }}</td>
                        <td data-title="Role">{{ $role->role->name }}</td>
                        @if ($role->event->getEventStatus() == 'Active')
                           <td data-title="Status" class="active">{{ $role->event->getEventStatus() }}</td>
                        @elseif ($role->event->getEventStatus() == 'Live')
                           <td data-title="Status" class="approved">{{ $role->event->getEventStatus() }}</td>
                        @elseif ($role->event->getEventStatus() == 'Past')
                           <td data-title="Status" class="cancel">{{ $role->event->getEventStatus() }}</td>
                        @endif
                        <td>
                           <a href="{{ route('events.show', $role->event->id) }}" class="view" title="View"><i class="la la-eye"></i></a>
                           <i class="la la-trash" title="Delete" data-bs-toggle="modal" data-bs-target="#delete-event-role-{{ $role->id }}"></i>
                        </td>
                     </tr>
                  @endforeach
               </tbody>
            </table>
         </div>
      </div>
   </div>
@endsection

resources/views/events/gifts.blade.php
@extends('layouts.master')
@section('title', 'Gifts Registry')
@section('content')
    <livewire:gift-registry :event="$event" />
@endsection

resources/views/events/manage-tickets.blade.php
@extends('layouts.master')
@section('title', 'Ticket Management')
@section('content')
<main id="main" class="site-main">
   <div class="site-content owner-content">
      <div class="container">
         <div class="member-place-wrap">
            <div class="member-wrap-top">
               <h2>Manage Tickets</h2>
               <div>
                  <a class="btn" href="{{ route('events.show', $event) }}">Back to My Event</a>
                  <a href="{{ route('client.event.guests', $event) }}" class="btn m-2 btn-info" style="background: #1DA1F2">Manage Guests</a>
                  <button class="btn m-2" style="background-color: #F58C1C" data-bs-toggle="modal" data-bs-target="#add-ticket-{{ $event->id }}">Add Ticket</button>
                  @include('partials.add-ticket')
               </div>
            </div><!-- .member-place-wrap -->
         </div><!-- .member-wrap-top -->
         <table class="member-place-list owner-booking table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th class="table-width-150">Ticket Title</th>
                    <th class="table-width-150">Ticket Price</th>
                    <th>Guest Limit</th>
                    <th>Description</th>
                    <th>Invited Guests No.</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
               <tr style="background: gray; color: white">
                  <td data-title="ID">
                     <p></p>
                  </td>
                  <td class="table-width-150">
                     General Admission
                  </td>
                  <td class="table-width-150">
                      <span>Ksh.0</span>
                  </td>
                  <td>
                     No Limit
                  </td>
                  <td></td>
                  <td>
                     {{ $event->getGeneralAdmissionGuestCount() }}
                  </td>
                  <td></td>
               </tr>
                @foreach ($tickets as $ticket)
                    <tr>
                        @include('partials.edit-ticket')
                        @include('partials.delete-event-ticket')
                        <td data-title="ID">
                           <p>{{ $i++ }}</p>
                        </td>
                        <td class="table-width-150">
                            {{$ticket->title }}
                        </td>
                        <td class="table-width-150">
                            <span>Ksh.{{ $ticket->price }}</span>
                        </td>
                        <td>
                           {{ $ticket->guest_limit }}
                        </td>
                        <td>
                           <span>
                              {{ $ticket->description }}
                           </span>
                        </td>
                        <td>
                           <span>{{ $ticket->getInvitedGuestsCount() }}</span>
                        </td>
                        <td>
                           <i class="la la-edit" data-bs-toggle="modal" data-bs-target="#edit-ticket-{{ $ticket->id }}" style="cursor: pointer"></i>
                           <i class="la la-trash" data-bs-toggle="modal" data-bs-target="#delete-ticket-{{ $ticket->id }}" style="cursor: pointer"></i>
                           {{-- <a href="{{ route('client.event.ticket.delete', $ticket->id) }}">
                              <i class="la la-trash" style="cursor: pointer"></i>
                           </a> --}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
         </table>
      </div>
   </div><!-- .site-content -->
</main><!-- .site-main -->
@endsection

resources/views/events/users.blade.php
@extends('layouts.master')
@section('title', 'Event Users')
@section('css')
   <style>
      @media only screen and (max-width: 992px) {
         .header-section > .btn {
            margin-top: 5px;
         }
      }
   </style>
@endsection
@section('content')
   <livewire:event-users-index :event="$event" />
@endsection