routes/web.php
<?php

use App\Jobs\SendSms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\EventProgramController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CustomerReviewController;
use App\Http\Controllers\ResolutionCenterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/login', [HomeController::class, 'index']);
Route::post('/login', [LoginController::class, 'sendLoginResponse'])->name('login');
Route::post('/register', [RegisterController::class, 'register'])->name('register');
Route::get('/register', [HomeController::class, 'index'])->name('register');
Route::get('/home', [HomeController::class, 'index'])->middleware(['auth', 'auth.session']);
Route::post('/search', [HomeController::class, 'searchServices'])->name('home.search');
Route::post('/search-event', [HomeController::class, 'searchEvents'])->name('home.event.search');
Route::get('/search-results/all', [HomeController::class, 'showSearchResults'])->name('search.show');
Route::post('/search-results', [HomeController::class, 'search'])->name('global.search');
Route::get('/auth/facebook', [SocialController::class, 'facebookRedirect'])->name('facebook.login');
Route::get('/auth/facebook/callback', [SocialController::class, 'facebookLogin']);
Route::get('/auth/google', [SocialController::class, 'redirectToGoogle'])->name('google.login');
Route::get('/auth/google/callback', [SocialController::class, 'handleGoogleCallback']);
Route::get('/forgot-password', [ResetPasswordController::class, 'enterEmail'])->name('password.request')->middleware('guest');
// Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email');
Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email.confirm');
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [ResetPasswordController::class, 'passwordUpdate'])->middleware('guest')->name('password.update');
Route::post('/dispute', [HomeController::class, 'fileDispute'])->name('dispute');
Route::resource('/resolution-center', ResolutionCenterController::class);
Route::post('/resolution-center/response', [ResolutionCenterController::class, 'issueResponse'])->middleware(['auth'])->name('resolution-center.response');

Route::get('/set-credentials', [UserController::class, 'setCredentials'])->name('set-credentials')->middleware('auth');
Route::post('/submit-credentials', [UserController::class, 'submitCredentials'])->name('submit-credentials')->middleware('auth');

Route::get('/set/phonenumber', [UserController::class, 'setPhoneNumber'])->name('set.phone');
Route::post('/submit/phonenumber', [UserController::class, 'submitPhoneNumber'])->name('submit.phone')->middleware('auth');
Route::get('/verify/phonenumber', [UserController::class, 'verifyPhoneForm'])->name('verify.phone');
Route::post('/phone/verify', [UserController::class, 'verifyPhoneNumber'])->name('submit.verify.phone')->middleware('auth');

// Route::get('/event/user/{email}/{eventId}/{role}/register', [HomeController::class, 'eventUserRegister'])->name('register.event.user');
Route::get('/event/{eventId}/user/{email}', [HomeController::class, 'eventUserRegister'])->name('register.event.user');

Route::get('/event/ticket/{guest}', [HomeController::class, 'ticket'])->name('event.ticket.show');
Route::post('/ticket/{ticket}/attended/guests', [EventController::class, 'eventTicketUpdateGuestsAttended'])->middleware(['auth', 'auth.session'])->name('event.guests.attended');
Route::post('/ticket/{ticket}/payment', [EventController::class, 'ticketPayment'])->name('ticket.payment');
Route::get('/event/guest/invite/{guest}', [HomeController::class, 'guestTicket']);

Auth::routes(['verify' => true, 'login' => false, 'register' => false]);

Route::view('/email/verify', 'verify')->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
   $request->fulfill();
   return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/resend/code', function() {
   SendSms::dispatch(Auth::user()->phone_number, 'Your verification code is '.Auth::user()->phone_verification_code);
   return redirect()->back()->with('success', 'Verification code sent');
});

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/faq', [SupportController::class, 'index'])->name('faq');
Route::get('vendor/view/{id}', [HomeController::class, 'viewVendor'])->name('vendor.view');
Route::get('user/profile/edit', [UserController::class, 'editProfile'])->name('user.profile.edit');
Route::post('user/profile/update', [UserController::class, 'updateProfile'])->name('user.profile.update');

Route::post('/customer-review', [CustomerReviewController::class, 'review'])->name('customer-review');

Route::group(['prefix' => 'events', 'as' => 'events.'], function () {
   Route::get('/', [EventController::class, 'index'])->name('index')->middleware(['auth', 'auth.session']);
   Route::get('/create', [EventController::class, 'create'])->name('create');
   Route::post('/store', [EventController::class, 'store'])->name('store');
   Route::post('/{id}/update', [EventController::class, 'update'])->name('update');
   Route::get('/{id}/show', [EventController::class, 'show'])->name('show')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/edit', [EventController::class, 'edit'])->name('edit')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/delete', [EventController::class, 'destroy'])->name('destroy')->middleware(['auth', 'auth.session']);
});

Route::get('/pricing/{id}', [CartController::class, 'getPricingPrice']);

Route::get('/messages', [MessagesController::class, 'index'])->name('messages');
Route::get('/messages/{orderID}', [MessagesController::class, 'chats'])->name('message.chat');
Route::post('/message/send', [MessagesController::class, 'store'])->name('message.send');
Route::post('/messages/name', [MessagesController::class, 'getUserName'])->name('message.user.name');

Route::group([
    'prefix' => 'client/',
    'as' => 'client.'
],function () {
   Route::get('/favorites', [HomeController::class, 'favorites'])->name('favorites');
    Route::post('create/event', [EventController::class, 'createEvent'])->name('create.event');
    Route::get('create/program', [HomeController::class, 'createProgram'])->name('create.program');
    Route::post('submit/program',  [HomeController::class, 'submitProgram'])->name('submit.program');
    Route::get('services/{category?}', [ServiceController::class, 'clientServices'])->name('services.all');
    Route::post('services', [ServiceController::class, 'clientServicesFiltered'])->name('services.filtered');
    Route::get('service/{service}', [ServiceController::class, 'clientService'])->name('service.one');
    Route::get('add-to-cart/{service}/{pricing?}', [ServiceController::class, 'addToCart'])->name('add-to-cart');
    Route::delete('remove-from-cart', [ServiceController::class, 'removeFromCart'])->name('remove-from-cart');
    Route::get('user/cart', [ServiceController::class, 'viewCart'])->name('user.cart');
    Route::get('event/{event}/tasks', [EventController::class, 'eventTasks'])->name('event.tasks')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/orders', [EventController::class, 'eventOrders'])->name('event.orders')->middleware(['auth', 'auth.session']);
    Route::get('/order/{order}', [OrderController::class, 'order'])->name('orders.order')->middleware(['auth', 'auth.session']);
    Route::post('event/order/delete', [EventController::class, 'deleteEventOrder'])->name('event.order.delete')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/add', [EventController::class, 'addEventTask'])->name('event.tasks.add')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/edit', [EventController::class, 'editEventTask'])->name('event.tasks.edit')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/gifts', [EventController::class, 'eventGifts'])->name('event.gifts');
    Route::post('event/{event}/gifts/gift/add', [EventController::class, 'addEventGift'])->name('event.gift.add')->middleware(['auth', 'auth.session']);
    Route::post('event/{gift}/gifts/gift/update', [EventController::class, 'updateEventGift'])->name('event.gift.update')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/guest/list', [EventController::class, 'eventGuestList'])->name('event.guests')->middleware(['auth', 'auth.session']);

app/Http/Livewire/AddToCart.php
<?php

namespace App\Http\Livewire;

use App\Models\Service;
use Livewire\Component;

class AddToCart extends Component
{
   public $service;

   public function addServiceToCart(Service $service)
   {
      $cart = session()->get('cart');

      if (!$cart) {
         $cart = [
            $service->id => [
               'service_pricing' => null
            ]
         ];

         session()->put('cart', $cart);

         dd(session()->get('cart'));

         return;
      }

      if (isset($cart[$service->id])) {
         dd('Service already in cart');
         return;
      }

      $cart[$service->id] = [
         'service_pricing' => null
      ];

      session()->put('cart', $cart);

      dd(session()->get('cart'));

   }
    public function render()
    {
        return view('livewire.add-to-cart');
    }
}

app/Http/Livewire/BudgetTransactions.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\BudgetTransaction;
use App\Models\Category;
use Livewire\WithPagination;

class BudgetTransactions extends Component
{
   use WithPagination;

   public $event;
   public $budget;
   public $title = '';
   public $type = "All";
   public $transaction_service_category = "All";

   public function paginationView()
   {
      return 'layouts.custom-paginate';
   }

   public function render()
   {
      $categories = Category::all()->pluck('name');
      $budgetTransactions = BudgetTransaction::
         where(['event_id' => $this->event->id, 'budget_id' => $this->budget->id])
         ->when($this->type && $this->type != 'All', function($query) {
            return $query->where('type', $this->type);
         })
         ->when(strlen($this->title) >= 3, function($query) {
            return $query->where('title', 'like', '%'.$this->title.'%');
         })
         ->when($this->transaction_service_category && $this->transaction_service_category != 'All', function($query) {
            return $query->where('transaction_service_category', $this->transaction_service_category);
         })
         ->paginate(10);
      $budgetTransactions->budget = BudgetTransaction::where(['event_id' => $this->event->id, 'budget_id' => $this->budget->id, 'type' => 'Top Up'])->sum('amount');
      $budgetTransactions->spent = BudgetTransaction::where(['event_id' => $this->event->id, 'budget_id' => $this->budget->id, 'type' => 'Expense'])->sum('amount');
      $budgetTransactions->balance = $budgetTransactions->budget - $budgetTransactions->spent;
      return view('livewire.budget-transactions', compact('budgetTransactions', 'categories'));
   }
}

app/Http/Livewire/CartNotifications.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Cart;

class CartNotifications extends Component
{
    public $itemsCount;

    protected $listeners = ['checkCart'];

    public function mount()
    {
        $this->itemsCount = Cart::where('user_id', auth()->user()->id)->count();
    }

    public function checkCart()
    {
        $this->getItemsCount();
    }

    public function getItemsCount()
    {
        if(auth()->guest()){
            session()->flash('error', 'Please login!');

            return;
        }

        $this->itemsCount = Cart::where('user_id', auth()->user()->id)->count();
    }
    public function render()
    {
        return view('livewire.cart-notifications');
    }
}

app/Http/Livewire/ClientCartView.php
<?php

namespace App\Http\Livewire;

use App\Models\Cart;
use App\Models\Event;
use Livewire\Component;
use App\Models\UserRole;
use Livewire\WithPagination;
use App\Models\ServicePricing;

class ClientCartView extends Component
{
   use WithPagination;

   public $item;
   public $servicePricing;
   public $orderMessage;

   public function paginationView()
   {
      return 'layouts.custom-paginate';
   }

   public function removeFromCart(Cart $cart)
   {
      $cart->delete();
      $this->reset();
      $this->emit('checkCart');
      session()->flash('success', "Removed from cart");
   }

   public function render()
   {
      $items = Cart::where('user_id', auth()->user()->id)->paginate(10);
      $items->load('service');
      $items->each(fn ($item) => $item->service->load('service_pricing'));
      $events = auth()->user()->events;

      // Check if user has been assigned roles
      if(auth()->user()->hasAssignedRoles()) {
         $roles = UserRole::where('user_id', auth()->id())->get();

         foreach ($roles as $role) {
            // Check if user role is 'Committee'
            if($role->role_id == 1) {
               $events->push(Event::find($role->event_id));
            }
         }
      }

      return view('livewire.client-cart-view')->with(['items' => $items, 'events' => $events]);
   }
}

app/Http/Livewire/ClientCheckout.php
<?php

namespace App\Http\Livewire;

use App\Models\Order;
use Livewire\Component;

class ClientCheckout extends Component
{
   public $orders;
   public $user;
   public $price;

   public function mount()
   {
      collect($this->orders);
   }

   public function deleteOrder(Order $order)
   {
      $this->orders = collect($this->orders)->filter(function($userOrder, $key) use ($order) {
         return $userOrder['id'] != $order->id;
      });
   }

   public function render()
   {
      return view('livewire.client-checkout');
   }
}

app/Http/Livewire/ClientServiceView.php
<?php

namespace App\Http\Livewire;

use App\Exceptions\DuplicateFavoriteException;
use App\Exceptions\DuplicateServiceException;
use App\Exceptions\FavoriteNotFoundException;
use App\Exceptions\ServiceNotFoundInCart;
use App\Models\Cart;
use App\Models\Favorites;
use App\Models\Service;
use Illuminate\Contracts\Session\Session;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class ClientServiceView extends Component
{
    public $service;
    public $isInFavorites;
    public $isInCart;

    public function mount(Service $service)
    {
        $this->service = $service;
        $this->isInFavorites = $service->isInUserFavorites(auth()->user());
        $this->isInCart = $service->isInCart(auth()->user());
    }

    public function addToFavorites()
    {
        if(auth()->guest()){
            session()->flash('error', 'Please login!');

            return;
        }

        if ($this->isInFavorites) {
            try {
                $this->service->removeFromFavorites(auth()->user());
            } catch (FavoriteNotFoundException $e) {
                //throw $th;
            }
            $this->isInFavorites = false;
        } else {
            try {
                $this->service->addToFavorites(auth()->user());
            } catch (DuplicateFavoriteException $e) {
                //throw $th;
            }

            $this->isInFavorites = true;
        }

    }

    public function addToCart()
    {
        if(auth()->guest()){
            session()->flash('error', 'Please login!');

            return;
        }

        if ($this->isInCart) {
            try {
                $this->service->removeFromCart(auth()->user());
            } catch (ServiceNotFoundInCart $e) {
                //throw $th;
            }
            $this->isInCart = false;
            $this->emit('checkCart');
        } else {
            try {
                $this->service->addServiceToCart(auth()->user());
            } catch (DuplicateServiceException $e) {
                //throw $th;
            }

            $this->isInCart = true;
            $this->emit('checkCart');
        }
    }

    public function render()
    {
        return view('livewire.client-service-view');
    }
}

app/Http/Livewire/ClientVendorView.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ClientVendorView extends Component
{
   public $vendor;

   public function render()
   {
      return view('livewire.client-vendor-view');
   }
}

resources/views/livewire/client-services-view.blade.php
<div>
   <div class="filter-group m-1">
      <div class="container">
         <form action="#" class="site__search__form mb-2 mf-right" wire:submit="searchServices" method="GET">
            <div class="row listing-box">
               <div class="col-lg-4 field-select">
                  <select name="category" wire:model="category" class="form-control">
                     <option value="All">All categories</option>
                     @foreach ($categories as $category)
                        <option value="{{ $category->name }}" class="mr-1">{{ $category->name }}</option>
                     @endforeach
                  </select>
               </div>
               <div class="col-lg-4">
                  <div class="field-group field-input">
                     <input wire:model="search" type="text" name="title" placeholder="Search Title">
                  </div><!-- .search__input -->
               </div>
               <div class="col-lg-4">
                  <div class="field-group field-select">
                     <select name="location" wire:model="location" class="form-control">
                        <option value="All">Select County</option>
                        <option value="All">All Counties</option>
                        @foreach ($counties as $county)
                           <option value="{{ $county['name'] }}">{{ $county['name'] }}</option>
                        @endforeach
                     </select>
                  </div><!-- .search__input -->
               </div>
            </div>
            @if (! collect($selectedCategories)->isEmpty() || $date != '' || $year != '' )
               <div class="service-filters">
                  @if ($year != '')
                     <span class="service-category-filter badge">{{ $year }} <span wire:click="removeYearFilter({{ $year }})" style="cursor: pointer"><i class="las la-times"></i></span></span>
                  @elseif($date != '')
                     <span class="service-category-filter badge">{{ $date }} <span wire:click="removeDateFilter({{ $date }})" style="cursor: pointer"><i class="las la-times"></i></span></span>
                  @endif
                  @foreach ($selectedCategories as $key => $value )
                     <span class="service-category-filter badge">{{ $value }} <span wire:click="removeCategory({{ $key }})" style="cursor: pointer"><i class="las la-times"></i></span></span>
                  @endforeach
               </div>
            @endif
         </form><!-- .search__form -->

         @if (! collect($selectedCategories)->isEmpty() || $date != '' || $year != '' || $search != '' || $location != '' )
            <a href="" wire:click.prevent="clearAllFilters" class="badge" style="background-color: #F58C1C; color: white">Clear All Filters</a>
         @endif
      </div>
   </div><!-- .filter-group -->

   <div class="archive-city layout-02">
      <div class="container">
         <div class="main-primary">
            <div class="top-area top-area-filter">
               <div class="filter-left">
                  <span class="result-count"><span class="count">{{ $services->count() }}</span> results</span>
               </div>
            </div>

            <div class="area-places layout-4col">
               @forelse ($services as $service)
                  <div class="place-item layout-02 place-hover">
                     <div class="place-inner">
                        <div class="place-thumb hover-img">
                           <a class="entry-thumb" href="{{ route('client.service.one', $service) }}"><img class="service-cover-image" src="{{ $service->getCoverImage($service->service_image) }}" alt="{{ $service->service_title }}" onerror="this.onerror=null; this.src='{{ $service->vendor->getCompanyLogo($service->vendor->company_logo) }}'"></a>
                           <div class="service_gallery_images_preview">
                              @if (count($service->service_images))
                                 <div class="service_images_preview">
                                    @foreach ($service->service_images->shuffle()->take(3) as $image)
                                       <img class="service_image_preview" src="{{ $service->getImage($image->image) }}" alt="{{ $service->service_title }}" onerror="this.onerror=null; this.src='{{ $service->vendor->getCompanyLogo($service->vendor->company_logo) }}'">
                                    @endforeach
                                 </div>
                              @endif
                           </div>
                           @auth
                              @if (auth()->user()->id != $service->vendor->user_id)
                                 <livewire:service-favorite :service="$service" :watched-file="$service->id" :key="now().$service->id" />
                              @endif
                           @endauth
                        </div>
                        <div class="entry-detail">
                           <div class="entry-head">
                              <div class="place-type list-item">
                                 <span>{{ $service->getCategory($service->category_id)->name }}</span>
                              </div>
                              <div class="place-city">
                                 <span>{{ $service->vendor->company_name }}</span>
                              </div>
                           </div>
                           <h3 class="place-title"><a href="{{ route('client.service.one', $service) }}">{{ $service->service_title }}</a></h3>
                           <div class="address" style="margin-top: -20px">
                              <i class="la la-map-marker"></i>
                              <span id="location">{{ $service->service_location }}</span>
                           </div>
                           <div class="entry-bottom">
                              <div class="place-preview">
                                 <div class="place-rating">
                                    <span>{{ $service->service_rating }}</span>
                                    <i class="la la-star"></i>
                                 </div>
                                 <span class="count-reviews">({{ $service->reviews->count() }} Reviews)</span>
                              </div>

                              @auth
                                 @if (auth()->user()->id != $service->vendor->user_id)
                                    {{-- <livewire:service-cart :service="$service" :watched-file="$service->id" :key="$service->id" /> --}}
                                    <div class="place-price" style="cursor: pointer">
                                       <a title="View Pricing Packages for the service" href="{{ route('client.service.one', $service) }}" style="font-size: 17px;">View Packages</a>
                                    </div>
                                 @endif
                              @else
                                 {{-- <a title="Cart" href="{{ route('client.add-to-cart', $service) }}"><i class="fa fa-shopping-cart" style="font-size: 14px; cursor: pointer"></i></a> --}}
                                 <a title="View Pricing Packages for the service" href="{{ route('client.service.one', $service) }}" style="font-size: 17px;">View Packages</a>
                              @endauth
                           </div>
                        </div>
                     </div>
                  </div>
               @empty
                  <p class="no-services-found-text">No services found</p>
               @endforelse
            </div>
            {{ $services->links() }}
         </div><!-- .main-primary -->
      </div><!-- .col-left -->
   </div><!-- .archive-city -->
</div>

resources/views/livewire/events-index.blade.php
<div>
   <div class="member-filter">
      <div class="mf-left">
         <form action="#" method="GET">
            <div class="row">
               <div class="col-lg-4 col-md-12 col-sm-12">
                  <div class="field-select">
                     <select name="place_cities" wire:model="perPage">
                        <option value="20">Show 10</option>
                        <option value="20">Show 20</option>
                        <option value="20">Show 40</option>
                        <option value="40">Show 60</option>
                        <option value="40">Show 100</option>
                     </select>
                     <i class="la la-angle-down"></i>
                  </div>
               </div>
               <div class="col-lg-4 col-md-12 col-sm-12">
                  <div class="field-select">
                     <select name="place_cities" wire:model="status">
                        <option value="All">All status</option>
                        <option value="Active">Active</option>
                        <option value="Past">Past</option>
                        <option value="Live">Live</option>
                     </select>
                     <i class="la la-angle-down"></i>
                  </div>
               </div>
               <div class="col-lg-4 col-md-12 col-sm-12">
                  <div class="field-group field-input">
                     <input type="phone_number" wire:model="search" class="form-control" placeholder="Search Name">
                  </div>
               </div>
            </div>
         </form>
      </div><!-- .mf-left -->
      <div class="mf-right">
         @if (Auth::user()->status === 'user' && Auth::user()->hasAssignedRoles())
            <div class="right-header__button btn" style="background-color: #000">
               <a href="{{ route('client.events.roles') }}">
                  Events With Roles
               </a>
            </div>
            @endif
         <div class="right-header__button btn">
            <a title="Create Your Own Event" href="{{ route('events.create') }}">
               <span>Create Event</span>
            </a>
         </div>
         <div class="right-header__button btn" style="background-color: #F58C1C">
            <a title="Create Your Own Event" href="{{ route('client.programs.index') }}">
               <span>My Programs</span>
            </a>
         </div>
      </div><!-- .mf-right -->
   </div><!-- .member-filter -->
   <table class="member-place-list owner-booking table-responsive">
      <thead>
      <tr>
         <th>#</th>
         <th class="table-width-200">Cover Photo</th>
         <th class="table-width-150">Event Name</th>
         {{-- <th class="table-width-200">Event Description</th> --}}
         <th class="table-width-200">Event Date</th>
         <th>Event Type</th>
         <th>Status</th>
         <th>Action</th>
      </tr>
      </thead>
      <tbody>
      @foreach($events as $event)
         <tr>
            <td>{{ $i++ }}</td>
            <td data-title="Cover Photo" class="service-img table-width-200">
               <a href="{{route('events.show', $event->id)}}">
                  <img src="{{ $event->getEventCoverImage($event->event_poster) }}" style="border-radius: 5px;" onerror="this.onerror=null; this.src='{{ $event->user->getAvatar($event->user->avatar) }}'" />
               </a>
            </td>
            <td data-title="Title" class="table-width-150">
               <a href="{{ route('events.show', $event->id) }}" style="cursor: pointer">
                  {{ $event->event_name }}
               </a>
            </td>
            <td data-title="Event Date" class="table-width-200">{{ Carbon\Carbon::parse($event->event_start_date)->format('M d, Y') }}</td>
            {{-- <td data-title="Description" class="event-description table-width-200">{{ $event->event_description }}</td> --}}
            <td data-title="Type">{{ $event->event_type }}</td>
            @if ($event->getEventStatus() == 'Active')
               <td data-title="Status" class="active">{{ $event->getEventStatus() }}</td>
            @elseif ($event->getEventStatus() == 'Live')
               <td data-title="Status" class="approved">{{ $event->getEventStatus() }}</td>
            @elseif ($event->getEventStatus() == 'Past')
               <td data-title="Status" class="cancel">{{ $event->getEventStatus() }}</td>
            @endif
            <td>
               <a href="{{ route('events.edit', $event->id) }}" class="edit" title="Edit"><i class="las la-edit"></i></a>
               <a href="{{ route('events.show', $event->id) }}" class="view" title="View"><i class="la la-eye"></i></a>
               <a href="{{ route('events.destroy', $event->id) }}" wire:click.prevent="deleteEvent({{ $event->id }})" class="delete" title="Delete"><i class="la la-trash"></i></a>
            </td>
         </tr>
      @endforeach
      </tbody>
   </table>
   {{ $events->links() }}
</div>

resources/views/livewire/order-status-view.blade.php
<h4 class="order-{{ $order->status }}">
   {{ $order->status }}
</h4>