routes/web.php
<?php

use App\Jobs\SendSms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\MessagesController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\EventProgramController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CustomerReviewController;
use App\Http\Controllers\ResolutionCenterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/login', [HomeController::class, 'index']);
Route::post('/login', [LoginController::class, 'sendLoginResponse'])->name('login');
Route::post('/register', [RegisterController::class, 'register'])->name('register');
Route::get('/register', [HomeController::class, 'index'])->name('register');
Route::get('/home', [HomeController::class, 'index'])->middleware(['auth', 'auth.session']);
Route::post('/search', [HomeController::class, 'searchServices'])->name('home.search');
Route::post('/search-event', [HomeController::class, 'searchEvents'])->name('home.event.search');
Route::get('/search-results/all', [HomeController::class, 'showSearchResults'])->name('search.show');
Route::post('/search-results', [HomeController::class, 'search'])->name('global.search');
Route::get('/auth/facebook', [SocialController::class, 'facebookRedirect'])->name('facebook.login');
Route::get('/auth/facebook/callback', [SocialController::class, 'facebookLogin']);
Route::get('/auth/google', [SocialController::class, 'redirectToGoogle'])->name('google.login');
Route::get('/auth/google/callback', [SocialController::class, 'handleGoogleCallback']);
Route::get('/forgot-password', [ResetPasswordController::class, 'enterEmail'])->name('password.request')->middleware('guest');
// Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email');
Route::post('/forgot-password', [ResetPasswordController::class, 'confirmEmail'])->middleware('guest')->name('password.email.confirm');
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
Route::post('/reset-password', [ResetPasswordController::class, 'passwordUpdate'])->middleware('guest')->name('password.update');
Route::post('/dispute', [HomeController::class, 'fileDispute'])->name('dispute');
Route::resource('/resolution-center', ResolutionCenterController::class);
Route::post('/resolution-center/response', [ResolutionCenterController::class, 'issueResponse'])->middleware(['auth'])->name('resolution-center.response');

Route::get('/set-credentials', [UserController::class, 'setCredentials'])->name('set-credentials')->middleware('auth');
Route::post('/submit-credentials', [UserController::class, 'submitCredentials'])->name('submit-credentials')->middleware('auth');

Route::get('/set/phonenumber', [UserController::class, 'setPhoneNumber'])->name('set.phone');
Route::post('/submit/phonenumber', [UserController::class, 'submitPhoneNumber'])->name('submit.phone')->middleware('auth');
Route::get('/verify/phonenumber', [UserController::class, 'verifyPhoneForm'])->name('verify.phone');
Route::post('/phone/verify', [UserController::class, 'verifyPhoneNumber'])->name('submit.verify.phone')->middleware('auth');

// Route::get('/event/user/{email}/{eventId}/{role}/register', [HomeController::class, 'eventUserRegister'])->name('register.event.user');
Route::get('/event/{eventId}/user/{email}', [HomeController::class, 'eventUserRegister'])->name('register.event.user');

Route::get('/event/ticket/{guest}', [HomeController::class, 'ticket'])->name('event.ticket.show');
Route::post('/ticket/{ticket}/attended/guests', [EventController::class, 'eventTicketUpdateGuestsAttended'])->middleware(['auth', 'auth.session'])->name('event.guests.attended');
Route::post('/ticket/{ticket}/payment', [EventController::class, 'ticketPayment'])->name('ticket.payment');
Route::get('/event/guest/invite/{guest}', [HomeController::class, 'guestTicket']);

Auth::routes(['verify' => true, 'login' => false, 'register' => false]);

Route::view('/email/verify', 'verify')->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
   $request->fulfill();
   return redirect('/');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::get('/resend/code', function() {
   SendSms::dispatch(Auth::user()->phone_number, 'Your verification code is '.Auth::user()->phone_verification_code);
   return redirect()->back()->with('success', 'Verification code sent');
});

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/faq', [SupportController::class, 'index'])->name('faq');
Route::get('vendor/view/{id}', [HomeController::class, 'viewVendor'])->name('vendor.view');
Route::get('user/profile/edit', [UserController::class, 'editProfile'])->name('user.profile.edit');
Route::post('user/profile/update', [UserController::class, 'updateProfile'])->name('user.profile.update');

Route::post('/customer-review', [CustomerReviewController::class, 'review'])->name('customer-review');

Route::group(['prefix' => 'events', 'as' => 'events.'], function () {
   Route::get('/', [EventController::class, 'index'])->name('index')->middleware(['auth', 'auth.session']);
   Route::get('/create', [EventController::class, 'create'])->name('create');
   Route::post('/store', [EventController::class, 'store'])->name('store');
   Route::post('/{id}/update', [EventController::class, 'update'])->name('update');
   Route::get('/{id}/show', [EventController::class, 'show'])->name('show')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/edit', [EventController::class, 'edit'])->name('edit')->middleware(['auth', 'auth.session']);
   Route::get('/{id}/delete', [EventController::class, 'destroy'])->name('destroy')->middleware(['auth', 'auth.session']);
});

Route::get('/pricing/{id}', [CartController::class, 'getPricingPrice']);

Route::get('/messages', [MessagesController::class, 'index'])->name('messages');
Route::get('/messages/{orderID}', [MessagesController::class, 'chats'])->name('message.chat');
Route::post('/message/send', [MessagesController::class, 'store'])->name('message.send');
Route::post('/messages/name', [MessagesController::class, 'getUserName'])->name('message.user.name');

Route::group([
    'prefix' => 'client/',
    'as' => 'client.'
],function () {
   Route::get('/favorites', [HomeController::class, 'favorites'])->name('favorites');
    Route::post('create/event', [EventController::class, 'createEvent'])->name('create.event');
    Route::get('create/program', [HomeController::class, 'createProgram'])->name('create.program');
    Route::post('submit/program',  [HomeController::class, 'submitProgram'])->name('submit.program');
    Route::get('services/{category?}', [ServiceController::class, 'clientServices'])->name('services.all');
    Route::post('services', [ServiceController::class, 'clientServicesFiltered'])->name('services.filtered');
    Route::get('service/{service}', [ServiceController::class, 'clientService'])->name('service.one');
    Route::get('add-to-cart/{service}/{pricing?}', [ServiceController::class, 'addToCart'])->name('add-to-cart');
    Route::delete('remove-from-cart', [ServiceController::class, 'removeFromCart'])->name('remove-from-cart');
    Route::get('user/cart', [ServiceController::class, 'viewCart'])->name('user.cart');
    Route::get('event/{event}/tasks', [EventController::class, 'eventTasks'])->name('event.tasks')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/orders', [EventController::class, 'eventOrders'])->name('event.orders')->middleware(['auth', 'auth.session']);
    Route::get('/order/{order}', [OrderController::class, 'order'])->name('orders.order')->middleware(['auth', 'auth.session']);
    Route::post('event/order/delete', [EventController::class, 'deleteEventOrder'])->name('event.order.delete')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/add', [EventController::class, 'addEventTask'])->name('event.tasks.add')->middleware(['auth', 'auth.session']);
    Route::post('event/tasks/edit', [EventController::class, 'editEventTask'])->name('event.tasks.edit')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/gifts', [EventController::class, 'eventGifts'])->name('event.gifts');
    Route::post('event/{event}/gifts/gift/add', [EventController::class, 'addEventGift'])->name('event.gift.add')->middleware(['auth', 'auth.session']);
    Route::post('event/{gift}/gifts/gift/update', [EventController::class, 'updateEventGift'])->name('event.gift.update')->middleware(['auth', 'auth.session']);
    Route::get('event/{event}/guest/list', [EventController::class, 'eventGuestList'])->name('event.guests')->middleware(['auth', 'auth.session']);

resources/views/layouts/about.blade.php
@extends('layouts.master')
@section('title', 'About')
@section('content')
   <div class="page-title page-title--small align-left" style="background-image: url(assets/images/bg/bg-about.png);">
      <div class="container">
         <div class="page-title__content">
               <h1 class="page-title__name">About Us</h1>
               <p class="page-title__slogan">Know more about us</p>
         </div>
      </div>
   </div><!-- .page-title -->
   <div class="site-content">
      <div class="container">
         <div class="company-info flex-inline">
            <img src="{{ $about->about_us_image }}" alt="Our Company">
            <div class="ci-content">
               <h2>About Tupange</h2>
               <p>{{ $about->content }}</p>
            </div>
         </div><!-- .company-info -->
         <br>
         <div class="owner-box">
            <div class="row">
               <div class="col-lg-4">
                  <div class="ob-item">
                     <div class="ob-head">
                        <h1>{{ $about->step_one_title }}</h1>
                     </div>
                     <div class="ob-content">
                        <span class="job">{{ $about->step_one_content }}</span>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4">
                  <div class="ob-item">
                     <div class="ob-head">
                        <h1>{{ $about->step_two_title }}</h1>
                     </div>
                     <div class="ob-content">
                        <span class="job">{{ $about->step_two_content }}</span>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4">
                  <div class="ob-item">
                     <div class="ob-head">
                        <h1>{{ $about->step_three_title }}</h1>
                     </div>
                     <div class="ob-content">
                        <span class="job">{{ $about->step_three_content }}</span>
                     </div>
                  </div>
               </div>
            </div>
         </div><!-- .owner-box -->
         <br>
         <div class="company-info flex-inline">
            <img src="{{ $about->for_planner_image }}" alt="Our Company">
            <div class="ci-content">
               <h2>For Planners</h2>
               <p>{{ $about->for_planner_content }}</p>

               <a href="{{ route('register') }}" class="btn btn-info open-signup" style="background-color: #1775B1" title="Register">Get Started</a>
            </div>
         </div><!-- .company-info -->
         <br>
         <div class="company-info flex-inline">
            <div class="ci-content">
               <h2>For Vendors</h2>
               <p>{{ $about->for_vendor_content }}</p>

               <a href="{{ route('login') }}" class="btn open-login" title="Login">Login to register as a vendor</a>
            </div>
            <img src="{{ $about->for_vendor_image }}" alt="Our Company">
         </div><!-- .company-info -->
         <br>
      </div>
   </div><!-- .site-content -->
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('home') }}">{{ __('Home') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('vendors') }}">{{ __('Vendors') }}</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/custom-paginate.blade.php
<div class="pagination align-left">
    <div class="pagination__numbers">
        @if($paginator->hasPages())
            @if (!$paginator->onFirstPage())
                <a wire:click.prevent="previousPage" title="Prev" href="#">
                    <i class="la la-angle-left"></i>
                </a>
            @endif
            <span>{{$paginator->currentPage()}}</span>
            @if($paginator->hasMorePages())
                <a wire:click.prevent="nextPage" title="Next" href="#">
                    <i class="la la-angle-right"></i>
                </a>
            @endif
        @endif
    </div>
</div>

resources/views/layouts/faqs.blade.php
@extends('layouts.master')
@section('title', 'FAQ\'s')
@section('content')
    <div class="page-title page-title--small align-left" style="background-image: url(assets/images/bg/bg-404.png);">
        <div class="container">
            <div class="page-title__content">
                <h1 class="page-title__name">FAQ's</h1>
                <p class="page-title__slogan">Frequently Asked Questions</p>
            </div>
        </div>
    </div><!-- .page-title -->
    <div class="site-content">
        <div class="container">
            <h2 class="title align-center">How may we be of help?</h2>
            <ul class="accordion first-open">
               @foreach ($faqs as $faq)
                  <li>
                     <h3 class="accordion-title"><a href="#">{{ $faq->question }}</a></h3>
                     <div class="accordion-content">
                        <p>{{ $faq->answer }}</p>
                     </div>
                  </li>
               @endforeach
            </ul>
        </div>
    </div><!-- .site-content -->
@endsection

resources/views/layouts/flash-message.blade.php
@push('scripts')
   <script>
      @if(Session::has('success'))
         toastr.options =
         {
               "closeButton" : true,
               "progressBar" : true,
               "positionClass" : "toast-bottom-right"
         }
         toastr.success("{{ session('success') }}");
         {{ session()->forget('success') }}
      @endif
      @if(Session::has('error'))
         toastr.options =
         {
               "closeButton" : true,
               "progressBar" : true,
               "positionClass" : "toast-bottom-right"
         }
         toastr.error("{{ session('error') }}");
         {{ session()->forget('error') }}
      @endif
      @if(Session::has('info'))
         toastr.options =
         {
               "closeButton" : true,
               "progressBar" : true,
               "positionClass" : "toast-bottom-right"
         }
         toastr.info("{{ session('info') }}");
         {{ session()->forget('info') }}
      @endif
      @if(Session::has('message'))
         toastr.options =
         {
               "closeButton" : true,
               "progressBar" : true,
               "positionClass" : "toast-bottom-right"
         }
         toastr.info("{{ session('message') }}");
         {{ session()->forget('message') }}
      @endif
      @if(Session::has('warning'))
         toastr.options =
         {
               "closeButton" : true,
               "progressBar" : true,
               "positionClass" : "toast-bottom-right"
         }
         toastr.warning("{{ session('warning') }}");
         {{ session()->forget('warning') }}
      @endif
   </script>
@endpush

resources/views/layouts/footer.blade.php
<footer id="footer" class="footer">
    <div class="container">
        <div class="footer__top">
            <div class="row">
                <div class="col-lg-5">
                    <div class="footer__top__info">
                        <a title="Logo" href="#" class="footer__top__info__logo"><img src="{{ asset('assets/images/assets/logo-1.png') }}" alt="Tupange"></a>
                        <p class="footer__top__info__desc">We want to help you with your event planning or services hunt that is why we provide you this platform. We believe you should have peace of mind when hiring service providers for your event so we give you a cash back guarantee on disputed cases. Create an account and start using our tools. Contact us if you need assistance.</p>
                    </div>
                </div>
                <div class="col-lg-2">
                    <aside class="footer__top__nav">
                        <h3>Company</h3>
                        <ul>
                            <li><a title="About Us" href="{{ url('/') }}">Home</a></li>
                            <li><a title="Blog" href="{{ route('about') }}">About</a></li>
                            <li><a title="Faqs" href="{{ route('faq') }}">Faqs</a></li>
                            {{-- <li><a title="Leave a comment" data-bs-toggle="modal" data-bs-target="#dispute" href="#">Leave a comment</a></li> --}}
                            <li><a title="Resolution Center" href="{{ route('resolution-center.index') }}">Resolution Center</a></li>
                        </ul>
                    </aside>
                </div>

                <div class="col-lg-3">
                    <aside class="footer__top__nav footer__top__nav--contact">
                        <h3>Contact Us</h3>
                        <p>Email: Tupangeevents@gmail.com</p>
                        <p>Phone: 0700776655</p>
                        <p>FCB, MIHRAB MEZZANINE 2</p>
                        <ul>
                            <li class="facebook">
                                <a title="Facebook" href="https://www.facebook.com/tupangeevents/" target="_blank">
                                    <i class="la la-facebook-f"></i>
                                </a>
                            </li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-2">
                  <aside class="footer__top__nav">
                      <ul>
                          <li><a title="Privacy Policy" href="#" data-bs-toggle="modal" data-bs-target="#privacy-policy">Privacy policy</a></li>
                          <li><a title="Terms of use" href="#" data-bs-toggle="modal" data-bs-target="#usage-terms">Terms of Use</a></li>
                          @auth
                          <li><a title="Leave a review" href="#" data-bs-toggle="modal" data-bs-target="#customer-review">Rate Tupange.com</a></li>
                              @if (auth()->user()->orders()->count() > 5)
                              @endif
                          @endauth
                      </ul>
                  </aside>
              </div>
            </div>
        </div><!-- .top-footer -->
        <div class="footer__bottom">
            <p class="footer__bottom__copyright">{{ now()->year }} &copy; <a title="Tupange Events" href="{{ url('/') }}" style="color: #8FCA27" >Tupange Events LTD</a>.All rights reserved.</p>
        </div><!-- .top-footer -->
    </div><!-- .container -->
</footer><!-- site-footer -->

resources/views/layouts/forgot-password.blade.php
@extends('layouts.master')
@section('title', 'Reset Password')
@section('css')
<style>
   .site-content {
      background-color: #F8F8F8;
   }
   .filter-group {
      background-color: #fff;
      width: 70%;
      margin-left: 15%;
      padding: 15px;
      border-radius: 10px;
      border: 1px solid #eeeeee;
   }
   .success-message {
      background-color: #529525;
      color: #fff;
      font-size: 18px;
      text-align: center;
      padding: 10px 10px;
      border: 1px solid #0b2007;
      border-radius: 5px;
   }
   @media only screen and (max-width: 768px) {
      .filter-group {
         width: 100%;
         margin-left: 0;
         margin-top: 20px;
      }
   }
</style>
@endsection
@section('content')
<div class="site-content owner-content">
   <div class="container">
      <div class="member-place-wrap">
         <div class="member-wrap-top">
            <h2>Reset Password</h2>
         </div><!-- .member-place-wrap -->
         <div class="filter-group">
            <form class="d-inline p-5" method="POST" action="{{ route('password.email.confirm') }}">
               @csrf
               <div>
                  <label for="email">Email</label>
                  <input type="phone_number" class="form-control" name="email" id="email" placeholder="Enter Email Here">
               </div>
               <x-input-error for="email" />
               <br>
               <div class="row">
                  <div class="col-6">
                     @if (Session::has('success'))
                        <p class="success-message">{{ session('success') }}</p>
                     @endif
                  </div>
                  <div class="col-6">
                     <button type="submit" class="btn btn-theme" style="float: right;">{{ __('Submit') }}</button>.
                  </div>
               </div>
           </form>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/layouts/reset-password.blade.php
@extends('layouts.master')
@section('title', "Reset Password")
@section('content')
<section class="bg-light">
   <div class="container-fluid">
       <div class="row justify-content-center">
           <div class="col-md-6">
               <div class="card">
           <div class="card-header"><h3>{{ __('Reset Password') }}</h3></div>

           <div class="card-body">
               <form method="POST" action="{{ route('password.update') }}">
                   @csrf

                   <input type="hidden" name="token" value="{{ $token }}">

                   <div class="form-group row">
                       <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                       <div class="col-md-6">
                           <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $email ?? old('email') }}" required autocomplete="email" autofocus>

                           @error('email')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                       </div>
                   </div>

                   <div class="form-group row">
                       <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                       <div class="col-md-6">
                           <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                           @error('password')
                               <span class="invalid-feedback" role="alert">
                                   <strong>{{ $message }}</strong>
                               </span>
                           @enderror
                       </div>
                   </div>

                   <div class="form-group row">
                       <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                       <div class="col-md-6">
                           <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                       </div>
                   </div>

                   <div class="form-group row mb-0">
                       <div class="col-md-6 offset-md-4">
                           <button type="submit" class="btn btn-primary">
                               {{ __('Reset Password') }}
                           </button>
                       </div>
                   </div>
               </form>
           </div>
       </div>
   </div>
</div>
</section>
@endsection